CREATE TABLE Miembro(
	miembroIdPK INTEGER NOT NULL PRIMARY KEY IDENTITY (-1,1),
	nombre VARCHAR(50) NOT NULL
);

CREATE TABLE Articulo(
	artIdPK INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
	titulo VARCHAR(max) NOT NULL,
	resumen VARBINARY(max) NOT NULL,
	miembroIdFK INTEGER NOT NULL DEFAULT -1,
	contenido VARBINARY(max) NOT NULL,
	tipoArt bit NOT NULL,
	extn VARCHAR(15)

	CONSTRAINT FK_Articulo_Miembro
		FOREIGN KEY(miembroIdFK) REFERENCES Miembro(miembroIdPK)
			ON DELETE SET DEFAULT
); 

CREATE TABLE Categoria(
	categoriaIdPK INTEGER NOT NULL PRIMARY KEY IDENTITY (-1,1),
	nombre VARCHAR(20) NOT NULL, 
);

CREATE TABLE Art_Categoria (
	categoriaIdFK INTEGER NOT NULL DEFAULT -1,
	artIdFK INTEGER NOT NULL
	
	CONSTRAINT PK_ArticuloCategoria PRIMARY KEY(categoriaIdFK,artIdFK)

	CONSTRAINT FK_Art_Categoria_Categoria
	FOREIGN KEY(categoriaIdFK) REFERENCES Categoria (categoriaIdPK)
		ON DELETE SET DEFAULT,

	CONSTRAINT FK_Art_Categoria_Articulo
	FOREIGN KEY(artIdFK) REFERENCES Articulo (artIdPK)
		ON DELETE CASCADE
);

CREATE TABLE Pregunta(
	pregIdPK INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
	pregunta VARCHAR(max) NOT NULL,
	miembroIdFK INTEGER DEFAULT -1,
	frecuente bit NOT NULL,

	CONSTRAINT FK_Pregunta_Miembro
		FOREIGN KEY(miembroIdFK) REFERENCES Miembro(miembroIdPK)
			ON DELETE SET DEFAULT
);

CREATE TABLE Respuesta(
	repId INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
	respuesta VARCHAR(max) NOT NULL,
	pregIdFK INTEGER NOT NULL,
	miembroIdFK INTEGER NOT NULL DEFAULT -1

	CONSTRAINT FK_Respuesta_Pregunta
		FOREIGN KEY(pregIdFK) REFERENCES Pregunta(pregIdPK)
			ON DELETE CASCADE,

	CONSTRAINT FK_Respuesta_Miembro
		FOREIGN KEY(miembroIdFK) REFERENCES Miembro(miembroIdPK)
		ON DELETE SET DEFAULT
);
