CREATE TABLE Miembros(
	miembroIdPK INTEGER NOT NULL PRIMARY KEY,
	userTypeID VARCHAR(20) NULL,
	nombre VARCHAR(20) NOT NULL
);

/*
CREATE TABLE Articulos(
	artIdPK INTEGER NOT NULL PRIMARY KEY,
	titulo VARCHAR(max) NOT NULL,
	resumen FILESTREAM/VARCHAR() NOT NULL,
	miembroIdFK INTEGER NOT NULL DEFAULT -1,
	contenido FILESTREAM NOT NULL,

	CONSTRAINT FK_miembro_articulo
		FOREIGN KEY(miembroIdFK) REFERENCES Miembros(miembroIdPK)
			ON DELETE SET DEFAULT
			ON UPDATE CASCADE
); 
*/

CREATE TABLE Categorias(
	categoriaIdPK INTEGER NOT NULL PRIMARY KEY,
	nombre VARCHAR(20) NOT NULL, 
	artIdFK INTEGER NOT NULL,

	CONSTRAINT FK_Categorias_Articulo
		FOREIGN KEY(artIdFK) REFERENCES Articulos(artIdPK)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

CREATE TABLE Preguntas(
	pregIdPK INTEGER NOT NULL PRIMARY KEY,
	pregunta VARCHAR(max) NOT NULL,
	miembroIdFK INTEGER DEFAULT -1,

	CONSTRAINT FK_Preguntas_Miembros
		FOREIGN KEY(miembroIdFK) REFERENCES Miembros(miembroIdPK)
			ON DELETE SET DEFAULT
			ON UPDATE CASCADE
);

CREATE TABLE Respuestas(
	repId INTEGER NOT NULL PRIMARY KEY,
	respuesta VARCHAR(max) NOT NULL,
	pregIdFK INTEGER NOT NULL,
	miembroIdFK INTEGER NOT NULL DEFAULT -1

	CONSTRAINT FK_Respuestas_Preguntas
		FOREIGN KEY(pregIdFK) REFERENCES Preguntas(pregIdPK)
			ON DELETE CASCADE,

	CONSTRAINT FK_Respuestas_Miembros
		FOREIGN KEY(miembroIdFK) REFERENCES Miembros(miembroIdPK)
		ON DELETE SET DEFAULT
		ON UPDATE CASCADE
);
